export const EDIT_PROFILE = 'APP/USER/EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'APP/USER/EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'APP/USER/EDIT_PROFILE_FAILURE';

export const SAVE_AVATAR = 'APP/USER/SAVE_AVATAR';
export const SAVE_AVATAR_SUCCESS = 'APP/USER/SAVE_AVATAR_SUCCESS';
export const SAVE_AVATAR_FAILURE = 'APP/USER/SAVE_AVATAR_FAILURE';